version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: bakery_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    # Removido autenticação para facilitar desenvolvimento
    volumes:
      - mongodb_data:/data/db
    networks:
      - bakery_network

  redis:
    image: redis:7-alpine
    container_name: bakery_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - bakery_network

  mongodb_test:
    image: mongo:7.0
    container_name: bakery_mongodb_test
    restart: unless-stopped
    ports:
      - "27018:27017"
    # Removido autenticação para facilitar testes
    volumes:
      - mongodb_test_data:/data/db
    networks:
      - bakery_network

volumes:
  mongodb_data:
  mongodb_test_data:

networks:
  bakery_network:
    driver: bridge

