import type { Metadata } from "next";
import { Fredoka } from "next/font/google";
import "./globals.css";

import { QueryProvider } from "../src/hooks/useCakes";
import { Sidebar } from "@/components/sidebar";
import { Header } from "@/components/header";
import { CartDrawer } from "@/components/cart-drawer";

const fredoka = Fredoka({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${fredoka.className} antialiased`}>
        <QueryProvider>
          <div className="flex h-screen overflow-hidden">
            <Sidebar />
            <div className="flex flex-1 flex-col overflow-hidden">
              <Header />
              <main className="flex-1 overflow-y-auto">{children}</main>
            </div>
            <CartDrawer />
          </div>
        </QueryProvider>
      </body>
    </html>
  );
}
